name: Spartan
main: me.vagdedes.spartan
version: 0.1-dummy
api-version: 1.13
description: Unofficial dummy repository for building
website: https://github.com/PikaMug/SpartanAPI-Dummy
authors: [Vagdedes, PikaMug]